image:
  repository: smeleshchyk/socketio-test
  tag: "0.0.2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

replicaCount: 1

extraEnv:
  - name: TEST__LOGIN_VAR
    valueFrom:
      secretKeyRef:
        name: socketio-test-service-env
        key: TEST__LOGIN_VAR
  - name: TEST_PASSWORD_VAR
    valueFrom:
      secretKeyRef:
        name: socketio-test-service-env
        key: TEST_PASSWORD_VAR
  - name: TEST_TOKEN_VAR
    valueFrom:
      secretKeyRef:
        name: socketio-test-service-env
        key: TEST_TOKEN_VAR